name: sheets-bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - watchdog=4.0.1
  - pandas=2.2.2
  - numpy=1.26.4
  - click=8.1.7
  - pytest=7.4.4
  - pytest-cov=4.1.0
  - ruff=0.4.4
  - black=24.4.2
  - tomli=2.0.1
  - pip=24.0
  - pip:
    - gspread==6.1.2
    - gspread-dataframe==3.3.1
    - pyyaml==6.0.1
    - requests==2.31.0
    - PySide6==6.7.*
    - pytest-qt 